repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.6
    hooks:
      # run the linter
      # - id: ruff
      #   args: [ --fix ]
      # run the formatter
      - id:  ruff-format