name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - ampl-mp=3.1.0=h2cc385e_1006
  - blas=1.0=mkl
  - bottleneck=1.3.5=py311hbed6279_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.7.22=hbcca054_0
  - contourpy=1.0.5=py311hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - expat=2.5.0=h6a678d5_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=58.2=he6710b0_3
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - ipopt=3.14.10=hf60ba86_0
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.4.4=py311h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20221030=h5eee18b_0
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_2
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=5_h92ddd45_netlib
  - libllvm14=14.0.6=hdb19cb5_3
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=hdbd6064_1
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hcbfbd50_0
  - libxslt=1.1.37=h2085143_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib=3.7.2=py311h06a4308_0
  - matplotlib-base=3.7.2=py311ha02d727_0
  - metis=5.1.0=h58526e2_1006
  - mkl=2023.1.0=h213fc3f_46343
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mpi=1.0=openmpi
  - mumps-include=5.2.1=ha770c72_11
  - mumps-mpi=5.2.1=hfb3545b_11
  - mumps-seq=5.2.1=h2104b81_11
  - munkres=1.1.4=py_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.8.7=py311h65dcdc2_0
  - numpy=1.26.0=py311h08b1b3b_0
  - numpy-base=1.26.0=py311hf175353_0
  - openjpeg=2.4.0=h3ad879b_0
  - openmpi=4.1.3=h8b79891_4
  - openssl=3.1.3=hd590300_0
  - packaging=23.1=py311h06a4308_0
  - pandas=2.0.3=py311ha02d727_0
  - parmetis=4.0.3=he9a3056_1005
  - pcre=8.45=h295c915_0
  - pillow=10.0.1=py311ha6cbd5a_0
  - pip=23.2.1=py311h06a4308_0
  - ply=3.11=py311h06a4308_0
  - ptscotch=6.0.9=hedbc1fb_1
  - pyparsing=3.0.9=py311h06a4308_0
  - pyqt=5.15.7=py311h6a678d5_0
  - pyqt5-sip=12.11.0=py311h6a678d5_0
  - python=3.11.5=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2023.3.post1=py311h06a4308_0
  - qt-main=5.15.2=h7358343_9
  - qt-webengine=5.15.9=h9ab4d14_7
  - qtwebkit=5.212=h3fafdc1_5
  - readline=8.2=h5eee18b_0
  - scalapack=2.2.0=h67de57e_1
  - scipy=1.11.3=py311h08b1b3b_0
  - scotch=6.0.9=h3858553_1
  - sip=6.6.2=py311h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.3.2=py311h5eee18b_0
  - tzdata=2023c=h04d1e81_0
  - unixodbc=2.3.12=h661eb56_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - ansicolors==1.1.8
      - aviary==0.2.1
      - build-pyoptsparse==2.0.6
      - certifi==2023.7.22
      - charset-normalizer==3.3.0
      - coverage==4.5.4
      - dymos==1.9.2.dev0
      - idna==3.4
      - mdolab-baseclasses==1.8.0
      - networkx==3.1
      - openmdao==3.28.1.dev0
      - parameterized==0.9.0
      - pyoptsparse==2.9.1
      - pyxdsm==2.3.0
      - requests==2.31.0
      - setuptools==65.7.0
      - simupy==1.1.2
      - sqlitedict==2.1.0
      - testflo==1.4.12
      - urllib3==2.0.6
prefix: /usr/share/miniconda/envs/test
