# Run Tests

name: Test with Pre-Release OpenMDAO/Dymos

on:

  # Run the workflow every Tuesday at 0400 UTC
  schedule:
    - cron: '1 4 * * 1,4'

  # Allow running the workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  test_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # latest released version of pyoptsparse
          # development versions of openmdao/dymos
          - NAME: dev
            PY: 3.12
            NUMPY: 1
            SCIPY: 1
            PYOPTSPARSE: 'latest'
            SNOPT: '7.7'
            #OPENMDAO: 'dev'
            OPENMDAO: '3.34.2'
            DYMOS: 'dev'

    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/actions
          path: actions

      - name: prepare_testing_environment
        uses: ./actions/.github/actions/prepare_environment
        with:
          NAME: ${{ matrix.NAME }}
          PY: ${{ matrix.PY }}
          NUMPY: ${{ matrix.NUMPY }}
          SCIPY: ${{ matrix.SCIPY }}
          PYOPTSPARSE: ${{ matrix.PYOPTSPARSE }}
          SNOPT: ${{ matrix.SNOPT }}
          OPENMDAO: ${{ matrix.OPENMDAO }}
          DYMOS: ${{ matrix.DYMOS }}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SNOPT_LOCATION_77: ${{ secrets.SNOPT_LOCATION_77 }}

      - name: Run tests
        shell: bash -l {0}
        run: |
          echo "============================================================="
          echo "Run Tests"
          echo "============================================================="
          testflo . -n 1 --timeout=200 --show_skipped --coverage --coverpkg aviary

      - name: Checkout actions (again)
        if: failure()
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github/actions
          path: actions

      - name: Send Email on failed tests
        if: failure()
        uses: ./actions/.github/actions/send_email
        with:
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: ${{ secrets.DESTINATION_EMAIL }}
          subject: "***Notification*** Tests failed with development versions of OpenMDAO/Dymos: ${{ github.run_id }}"
          body: |
            {
              "title": "Test with Pre-Release OpenMDAO/Dymos",
              "action": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
