# Run Tests

name: Aviary Tests

on:
  # Trigger on push or pull request events for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]
  merge_group:
    branches: [ main ]

  # Allow running the workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  pre_commit:
    # run pre-commit checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - uses: pre-commit/action@v3.0.1

  test_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # oldest versions of openmdao/dymos
          - NAME: oldest
            PY: '3.9'
            NUMPY: '1.20'
            SCIPY: '1.6'
            PYOPTSPARSE: 'v2.9.1'
            SNOPT: '7.7'
            OPENMDAO: 'dev'
            DYMOS: '1.8.0'

          # latest versions of openmdao/dymos
          - NAME: latest
            PY: '3.10'
            NUMPY: 1
            SCIPY: 1
            PYOPTSPARSE: 'v2.9.1'
            SNOPT: '7.7'
            OPENMDAO: 'dev'
            DYMOS: 'latest'

          # development versions of openmdao/dymos
          - NAME: dev
            PY: 3
            NUMPY: 1
            SCIPY: 1
            PYOPTSPARSE: 'v2.9.1'
            SNOPT: '7.7'
            OPENMDAO: 'dev'
            DYMOS: 'dev'

    steps:      
      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/actions
          path: actions

      - name: prepare_docs_environment
        uses: ./actions/.github/actions/prepare_environment
        with:
          NAME: ${{ matrix.NAME }}
          PY: ${{ matrix.PY }}
          NUMPY: ${{ matrix.NUMPY }}
          SCIPY: ${{ matrix.SCIPY }}
          PYOPTSPARSE: ${{ matrix.PYOPTSPARSE }}
          SNOPT: ${{ matrix.SNOPT }}
          OPENMDAO: ${{ matrix.OPENMDAO }}
          DYMOS: ${{ matrix.DYMOS }}
          Run_tests: true
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SNOPT_LOCATION_77: ${{ secrets.SNOPT_LOCATION_77 }}